version: 2.1

jobs:
  linting:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run Lint
          command: |
            . venv/bin/activate
            make lint

  testing:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Run Test
          command: |
            . venv/bin/activate
            make test

  push_docker_containers_to_dockerhub:
    docker:
      - image: circleci/golang:1.15
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker Image
          command: |
            docker build --tag=my-capstone-project-$CIRCLE_WORKFLOW_ID .
            # List docker images
            docker image ls
            docker run -d -p 5000:5000 my-capstone-project-$CIRCLE_WORKFLOW_ID
            dockerpath=sayyedmo/my-capstone-project
            # Authenticate & tag
            docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
            echo "Docker ID and Image: $dockerpath"
            docker tag my-capstone-project-$CIRCLE_WORKFLOW_ID sayyedmo/my-capstone-project:$CIRCLE_WORKFLOW_ID
            # Push image to a docker repository
            docker push sayyedmo/my-capstone-project:$CIRCLE_WORKFLOW_ID
  create_EKS_cluster:
    docker:
      - image: python:3.7-alpine3.11
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install EKSCTL Tool
          command: |
            apk add --update tar gzip  curl
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/v0.83.0/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp
            mv /tmp/eksctl /usr/local/bin
      - run:
          name: Create EKS Cluster
          command: |
            eksctl create cluster --name=myEKSCluster-$CIRCLE_WORKFLOW_ID

  deploy_app_to_cluster:
    docker:
      - image: python:3.7-alpine3.11
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Kubectl Tool
          command: |
            apk add --update curl
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            kubectl version --client
      - run:
          name: Deploy App To Cluster
          command: |
            # Deploy an App from the Dockerhub to the Kubernetes Cluster
            kubectl create deploy my-capstone-project-$CIRCLE_WORKFLOW_ID --image=sayyedmo/my-capstone-project:$CIRCLE_WORKFLOW_ID
            # See the status
            app_pod = kubectl get pods --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}'
            # Port forward
            kubectl port-forward $app_pod --address 0.0.0.0 5000:5000


workflows:
  default:
    jobs:
    - Liniting
    - Testing:
        requires: [Liniting]
    - push_docker_containers_to_dockerhub:
        requires: [Testing]
    - create_EKS_cluster:
        requires: [push_docker_containers_to_dockerhub]
    - deploy_app_to_cluster:
        requires: [create_EKS_cluster]